### PR TITLE
fix: badgerdb preventing from loading on Windows

### LINKED ISSUE #705: Windows configuration - Application setup issue
**Describe the bug**
I am receiving the below error while doing the application setup in my local windows system :

Error: Could not config mailbox store: During db.vlog.open: Value log truncate required to run DB. This might result in data loss

**To Reproduce**
1. Go to 'https://github.com/mailchain/mailchain/blob/master/DEVELOPMENT_GUIDE.md'
2. Go to "Add account" and run "go run cmd/mailchain/main.go account add --protocol=ethereum --key-type="secp256k1" --private-key=YOUR_PRIVATE_KEY". 
3.  After adding an account, scroll down to "Serve" and run "go run cmd/mailchain/main.go serve". 

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version:  v0.0.69`

**Expected behavior**
The expected behavior should be a running instance of mailchain application in local.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by sa3664**
As per the recommendation on the official badger GitHub repo on https://github.com/dgraph-io/badger/issues/246 , I have applied the fix .

### CODE REVIEW

File: stores/bdbstore/badgerdb.go [hunk 1]
```diff
@@ -69,7 +71,8 @@ type Database struct {
 func New(dir string, logWriter io.Writer) (*Database, error) {
 	opts := badger.DefaultOptions(dir)
 	opts.Logger = newLogger(logWriter)
-
+	opts.Truncate = true
+	opts.ValueLogLoadingMode = options.FileIO
```
Comment (robdefeo) [inline stores/bdbstore/badgerdb.go:75]: I wasn't aware of this option. Learnt something new :)

**Review by robdefeo — APPROVED** [review]
Thanks @sa3664 for finding this issue and fixing it 😄  The fix looks good. I'm going to change the name of the PR to the semantic naming conventions as the PR names form the release log. https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

It's good to merge. 👍

**Comment by robdefeo** [comment]
fixes #705
