### PR TITLE
#406 HTML Detection Fails on Send Message

### LINKED ISSUE #406: HTML Detection Fails on Send Message
**Describe the bug**
When I send a message with an HTML body, it appears mailchain is appending the following `/r/n`
```
"body":"<h2>Heading 1</h2><h3>Heading 2</h3><h4>Heading 3</h4><p>Paragraph</p><p>Some bold text: <strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.</strong></p><p>Some italic text: <i>Lorem ipsum dolor sit amet consectetur adipisicing elit.</i></p><p>Some linked text: Lorem ipsum dolor sit amet consectetur adipisicing elit.</p><p>3 Bullets:</p><ul><li>Lorem</li><li>ipsum dolor sit</li><li>amet consectetur adipisicing elit.</li></ul><p>3 numbers:</p><ol><li>Lorem</li><li>ipsum dolor sit</li><li>amet consectetur adipisicing elit.</li></ol><blockquote><p>Quoted text: Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.</p></blockquote><p>&nbsp;</p><p><strong>Table</strong>:</p><figure class=\"table\"><table><tbody><tr><td>Row1</td><td>col2</td><td>col3</td></tr><tr><td>Row2</td><td>col2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.&nbsp;</td><td>col3</td></tr><tr><td>Row3</td><td>col2</td><td>col3</td></tr></tbody></table></figure>"
```
**To Reproduce**
The following curl request fails.Update the right send for an address you control.

```
curl 'http://127.0.0.1:8080/api/messages?protocol=ethereum&network=ropsten' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Origin: http://localhost:4200' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Referer: http://127.0.0.1:8080/' \
  -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  --data-binary '{"message":{"body":"<h2>Heading 1</h2><h3>Heading 2</h3><h4>Heading 3</h4><p>Paragraph</p><p>Some bold text: <strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.</strong></p><p>Some italic text: <i>Lorem ipsum dolor sit amet consectetur adipisicing elit.</i></p><p>Some linked text: Lorem ipsum dolor sit amet consectetur adipisicing elit.</p><p>3 Bullets:</p><ul><li>Lorem</li><li>ipsum dolor sit</li><li>amet consectetur adipisicing elit.</li></ul><p>3 numbers:</p><ol><li>Lorem</li><li>ipsum dolor sit</li><li>amet consectetur adipisicing elit.</li></ol><blockquote><p>Quoted text: Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.</p></blockquote><p>&nbsp;</p><p><strong>Table</strong>:</p><figure class=\"table\"><table><tbody><tr><td>Row1</td><td>col2</td><td>col3</td></tr><tr><td>Row2</td><td>col2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit saepe voluptatibus cum numquam ex facere pariatur temporibus vitae quis obcaecati praesentium optio id minima magnam, libero possimus nihil vel expedita.&nbsp;</td><td>col3</td></tr><tr><td>Row3</td><td>col2</td><td>col3</td></tr></tbody></table></figure>","headers":{"from":"0x92d8f10248c6a3953cc3692a894655ad05d61efb","reply-to":"0x92d8f10248c6a3953cc3692a894655ad05d61efb","to":"0xd5ab4ce3605cd590db609b6b5c8901fdb2ef7fe6"},"public-key":"0x69d908510e355beb1d5bf2df8129e5b6401e1969891e8016a0b2300739bbb00687055e5924a2fd8dd35f069dc14d8147aa11c1f7e2f271573487e1beeb2be9d0","subject":"html 5"}}' \
  --compressed
  
```

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.1.0`

**Expected behavior**
The `/r/n` should not be appended, which will make the `"content-type": "text/plain; charset=\"UTF-8\""` come back as `"content-type": "text/html; charset=\"UTF-8\""`

**Screenshots**
image

**Desktop (please complete the following information):**
 - Version 0.0.37

### PR DESCRIPTION
**Pull request by nikosk686**
Adds optional content-type field on send message request.
If content-type is missing defaults to text/plain
Closes #406

### CODE REVIEW

File: internal/mail/headers.go [hunk 1]
```diff
@@ -19,7 +19,11 @@ import (
 )
 
 // DefaultContentType value.
-const DefaultContentType = "text/plain; charset=\"UTF-8\""
+const (
+	HtmlContentType    = "text/html; charset=\"UTF-8\""
```
Comment (golangcibot) [inline internal/mail/headers.go]: const `HtmlContentType` should be `HTMLContentType` (from `golint`)

File: internal/mail/message_test.go [hunk 2]
```diff
@@ -71,38 +133,38 @@ func TestNewMessage(t *testing.T) {
 
 func Test_detectContentType(t *testing.T) {
```
Comment (robdefeo) [inline internal/mail/message_test.go]: Can you rename this test function to `Test_contentTypeOrDefault`

Comment (nikosk686) [reply internal/mail/message_test.go]: Done!
