### PR TITLE
maps name service endpoint's not found error to the rfc 1035 specification's associated one

### LINKED ISSUE #242: Name Service endpoint throws 404 error for name/address not found
**Describe the bug**
When calling endpoints with a valid name/address but one that does not have a resolvable ENS name/address, the API response is a 404.

* http://127.0.0.1:8080/api/nameservice/address/{address}/resolve?protocol=ethereum&network=ropsten
* http://127.0.0.1:8080/api/nameservice/name/{name}/resolve?protocol=ethereum&network=ropsten

This is a arguably correct response for no name existing, but it leads to degraded developer/user experience as:
[1] The 'not found' error needs to be handled as part of the application flow, as an expected result.
[2] The error is propagated to the browser console and looks, well, ugly 👹

**To Reproduce**
1. Go to 'https://inbox.mailchain.xyz/#/' with mailchain client running with addresses that are not configured for reverse resolution in ENS 
2. Open the javascript console
3. See error

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.31`

**Expected behavior**
Something more graceful - open to ideas that help the developer handle errors better

### PR DESCRIPTION
**Pull request by nikosk686**
Closes #242

### CODE REVIEW

**Comment by nikosk686** [comment]
Fixing the coverage issue

File: nameservice/errors.go [hunk 1]
```diff
@@ -26,8 +26,25 @@ var (
 	ErrNotFound        = errors.New("not found")
 	ErrInvalidName     = errors.New("invalid name")
 	ErrInvalidAddress  = errors.New("invalid address")
+
+	// RFC 1035 error interpretation
+	ErrNon      = errors.New("No Error")
```
Comment (robdefeo) [inline nameservice/errors.go]: Its best to remove this as its unclear it no error is not an error. E.g. you'd have to do something like
```
if err!=nil && err != ErrNon{
....
}
```

File: nameservice/errors.go [hunk 2]
```diff
@@ -61,3 +78,18 @@ func IsInvalidAddressError(err error) bool {
...
 }
+
+func IsRfc1035Error(err error) bool {
+	_, ok := Rfc1035StatusMap[err]
+	return ok
+}
+
+func wrapError(err error) error {
+	if err == nil {
+		return ErrNon
```
Comment (robdefeo) [inline nameservice/errors.go]: Best just to return `nil` here as then downstream it can be dealt with as a nil error the same as others

File: nameservice/errors.go [hunk 3]
```diff
@@ -26,8 +26,25 @@ var (
 	ErrNotFound        = errors.New("not found")
```
Comment (robdefeo) [inline nameservice/errors.go]: It would best if your PR removed the previous errors
```
ErrUnableToResolve = errors.New("unable to resolve")
	ErrNotFound        = errors.New("not found")
	ErrInvalidName     = errors.New("invalid name")
	ErrInvalidAddress  = errors.New("invalid address")
```
Instead the new errors you created are used, see other notes as to where changes would be made to use the new errors. 
One additional change that would need to be made is in `ens/errors.go`
```
func wrapError(err error) error {
	if err == nil {
		return nil
	}
	switch fmt.Sprintf("%v", errors.Cause(err)) {
	case fmt.Sprintf("%v", errors.Cause(errors.Errorf("no resolver"))),
		fmt.Sprintf("%v", errors.Cause(errors.Errorf("No resolution"))):
		return errors.WithMessage(err, nameservice.ErrUnableToResolve.Error())

	case fmt.Sprintf("%v", errors.Cause(errors.Errorf("unregistered name"))):
		return errors.WithMessage(err, nameservice.ErrNotFound.Error())

	case fmt.Sprintf("%v", errors.Cause(errors.Errorf("could not parse address"))):
		// address related to not being able to part ens address not ethereum address
		return errors.WithMessage(err, nameservice.ErrInvalidName.Error())

	default:
		return err
	}
}
```
Based on the switch statement, I'd suggest per case these errors`ErrUnableToResolve`, `ErrInvalidName`, `ErrInvalidAddress` you can remove `IsNoResolverError`, `IsNotFoundError`, `IsInvalidNameError`, `IsInvalidAddressError`

This way ENS, will resolve an unknown `err` e.g. default condition, or a known error one of the case statements. The calling code only needs to use your `IsRfc1035Error` function to determine this.

File: cmd/mailchain/internal/http/handlers/resolve_address.go [hunk 4]
```diff
@@ -60,6 +60,12 @@ func GetResolveAddress(resolvers map[string]nameservice.ReverseLookup) func(w ht
 			errs.JSONWriter(w, http.StatusNotAcceptable, errors.Errorf("%q not supported", protocol+"/"+network))
 			return
 		}
+		if nameservice.IsRfc1035Error(err) {
```
Comment (robdefeo) [inline cmd/mailchain/internal/http/handlers/resolve_address.go]: this will be the only `nameservice.Is....` function needed as the later comments explain how to remove the other functions

File: cmd/mailchain/internal/http/handlers/resolve_name.go [hunk 5]
```diff
@@ -60,6 +60,12 @@ func GetResolveName(resolvers map[string]nameservice.ForwardLookup) func(w http.
 			errs.JSONWriter(w, http.StatusNotAcceptable, errors.Errorf("%q not supported", protocol+"/"+network))
 			return
 		}
+		if nameservice.IsRfc1035Error(err) {
```
Comment (robdefeo) [inline cmd/mailchain/internal/http/handlers/resolve_name.go]: this will be the only `nameservice.Is....` function needed as the later comments explain how to remove the other functions

File: nameservice/errors.go (hunk 3 above)
Comment (robdefeo) [reply nameservice/errors.go]: To clarify the above comment as I have made a mistake explaining which errors should be used to replace the old ones. Regarding mapping of errors, I'd suggest something like
```
func wrapError(err error) error {
	if err == nil {
		return nil
	}
	switch fmt.Sprintf("%v", errors.Cause(err)) {
	case fmt.Sprintf("%v", errors.Cause(errors.Errorf("no resolver"))),
		fmt.Sprintf("%v", errors.Cause(errors.Errorf("No resolution"))):
		return errors.WithMessage(err, nameservice.ErrNXDomain.Error())

	case fmt.Sprintf("%v", errors.Cause(errors.Errorf("unregistered name"))):
		return errors.WithMessage(err, nameservice.ErrNXDomain.Error())

	case fmt.Sprintf("%v", errors.Cause(errors.Errorf("could not parse address"))):
		// address related to not being able to part ens address not ethereum address
		return errors.WithMessage(err, nameservice.ErrFormat.Error())

	default:
		return err
	}
}
```

**Comment by nikosk686** [comment]
Trying to fix coverage issues.
Meanwhile, @robdefeo you could have a look on the changes.
I am not sure that they are totally aligned to your previous comments.
Please, let me know if further changes are needed or if I took the wrong way anyway :)

**Comment by robdefeo** [comment]
Thanks @nikosk686 🍾 for your work on this issue and in your patience in working through the problem to good solution. Really enjoyed that you were able to remove code while adding extra functionality.
