### PR TITLE
fix: return correct code from nameservice

### LINKED ISSUE #595: bug: Address is returned incorrectly by /nameservice/name/.../resolve endpoint
**Describe the bug**

When I try to resolve an unregistered ENS name that has its resolver set to `0x0000000000000000000000000000000000000000`, the response from the API is:

```
{"address":"0x","status":0}
```

If this reducing down the zeros (i.e. handling it as a number)? Or something else?

**To Reproduce**
1. Run `mailchain serve`
2. Browse to `http://127.0.0.1:8080/api/nameservice/name/alf.eth/resolve?protocol=ethereum&network=mainnet`

**What version of Mailchain are you using ?**
`$ mailchain version`
`Version: v0.0.48`

**Expected behavior**
It should return:

```
{"address":"0x0000000000000000000000000000000000000000","status":0}
```

### PR DESCRIPTION
**Pull request by robdefeo**
closes #595

### CODE REVIEW

File: cmd/mailchain/internal/http/handlers/resolve_name.go [hunk 1]
```diff
@@ -64,10 +64,8 @@ func GetResolveName(resolvers map[string]nameservice.ForwardLookup) func(w http.
 			errs.JSONWriter(w, http.StatusNotAcceptable, errors.Errorf("%q not supported", protocol+"/"+network))
 			return
 		}
-		if nameservice.IsRFC1035Error(err) {
-			_ = json.NewEncoder(w).Encode(GetResolveNameResponseBody{
-				Status: nameservice.RFC1035StatusMap[err],
-			})
+		if nameservice.ErrorToRFC1035Status(err) > 0 {
```
Comment (golangcibot) [inline cmd/mailchain/internal/http/handlers/resolve_name.go]: if statements should only be cuddled with assignments (from `wsl`)
